apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-k8s
spec:
  selector:
    matchLabels:
      app: nestjs-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: nestjs-k8s
    spec:
      containers:
        - name: nestjs-k8s
          image: multiplexor88/nestjs-k8s
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: config-map
            - secretRef:
                name: secret

